### PR TITLE
Modernize Build System

### PR DESCRIPTION
**Pull request by carstene1ns**
* Updated URLs, version
* `pkg-config` support
* easier cross-compilation, less Windows-specific hacks
* parallel compilation support
* less verbose output by default

### CODE REVIEW

**Comment by carstene1ns** [comment]
ping

**Comment by carstene1ns** [comment]
pong

**Comment by grom358** [comment]
Sorry I don't keep up much on this project. I just this week decided to update the builds to work on latest cygwin and mingw.. Or at least still trying.

Will try this branch.

**Comment by grom358** [comment]
How do you have you IL headers setup? I can't get past it saying I need DevIL where it built on master.

**Pull request merged**
